spring:
 rabbitmq:
  host: localhost
  username: rmq_admin
  password: rmq_admin
  port: 5672
queue:
 name:
  read: "treehouse"
  write: "leaf-rake"
crawler:
 politeness:
  timeout: 
   tokopedia: 1000